"""Build an offline comparison from actual Unreal captures only."""
from pathlib import Path
root=Path(r'D:/UE5Projects/GameAnimationSample/Saved/Mazzarino80/Preview/Historic')
views=[('after','Dalla strada'),('after_alley','Nel vicolo'),('after_skyline','Volumi e coperture'),('after_gray','Forme senza texture'),('after_gray_alley','Vicolo in grigio'),('after_gray_skyline','Panoramica in grigio')]
parts=[]
for name,title in views:
 for folder in ['BeforeDetails','Details']:assert (root/folder/(name+'.png')).exists()
 parts.append(f'''<section><h2>{title}</h2><div class="compare"><img src="Details/{name}.png" alt="Dopo: {title}"><img class="before" src="BeforeDetails/{name}.png" alt="Prima: {title}"><span class="tag left">Prima</span><span class="tag right">Dopo</span><div class="line"></div></div><label>Trascina per confrontare <input aria-label="Confronto {title}" type="range" min="0" max="100" value="50"></label><details><summary>Vedi entrambe le immagini intere</summary><div class="pair"><figure><img src="BeforeDetails/{name}.png"><figcaption>Prima della rifinitura</figcaption></figure><figure><img src="Details/{name}.png"><figcaption>Dopo</figcaption></figure></div></details></section>''')
html='''<!doctype html><html lang="it"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Mazzarino — confronto delle 18 case</title><style>
*{box-sizing:border-box}body{margin:0;background:#171a1d;color:#ede8dd;font:17px/1.55 system-ui,sans-serif}main{max-width:1200px;margin:auto;padding:40px 22px}h1{font-size:clamp(29px,4vw,46px);line-height:1.1}h2{font-size:24px}p{max-width:880px;color:#c5c5bd}.eyebrow{color:#dcb685;letter-spacing:.12em;font-size:13px}section{margin:45px 0}.compare{position:relative;aspect-ratio:1.6;overflow:hidden;border-radius:8px;background:#333}.compare img{position:absolute;width:100%;height:100%;object-fit:contain}.before{clip-path:inset(0 50% 0 0)}.line{position:absolute;left:50%;top:0;height:100%;width:2px;background:white;pointer-events:none}.tag{position:absolute;top:14px;padding:5px 12px;background:#111c;border-radius:5px;font-size:14px}.left{left:14px}.right{right:14px}label{display:flex;gap:18px;align-items:center;margin:14px 0;font-size:14px}input{flex:1;accent-color:#dfb47d}summary{cursor:pointer;color:#dcb685}.pair,.details{display:grid;grid-template-columns:1fr 1fr;gap:16px}.pair img,.details img{width:100%;border-radius:7px}figure{margin:16px 0}figcaption{font-size:14px;color:#b7bbb9}.note{border-left:3px solid #bd9b6d;padding:0 18px}ul{padding-left:23px}a{color:#edbc7d}@media(max-width:650px){.pair,.details{grid-template-columns:1fr}label{display:block}input{width:100%}}
</style><main><div class="eyebrow">MAZZARINO · CAMPIONE DI 18 CASE · 28 SETTEMBRE 2026</div><h1>Volumi chiusi, dettagli con profondità</h1><p>Confronto tra la versione precedente delle 18 case e la rifinitura attuale. Tutte le immagini provengono dall'editor Unreal, con le stesse camere per ogni coppia. Le viste grigie isolano la forma delle case; chiesa e strutture recuperate conservano i materiali originali.</p><ul><li>Davanzali ridotti a 5,5 cm; pareti e raccordi chiusi.</li><li>Coppi tridimensionali, balconi completi e ringhiere con sezioni tonde.</li><li>Cavi e pluviali su spline modificabili; cinque facciate in muratura a vista.</li></ul>'''+''.join(parts)+'''<section><h2>I nuovi dettagli</h2><div class="details"><figure><img src="Details/detail_roof.png" alt="Dettaglio dei coppi tridimensionali"><figcaption>Coppi modellati, colmo e variazione dell'argilla.</figcaption></figure><figure><img src="Details/detail_balcony.png" alt="Balcone completo recuperato da Comune"><figcaption>Modulo di Comune sulle case curate: balaustra, lastra e sostegni.</figcaption></figure></div></section><section class="note"><h2>Verifica e limiti</h2><p>Salvataggio e riapertura verificati: 18 case, 112 spline di impianti, 28.259 coppi e 9 balconi completi conservati. I perimetri sono invariati e le case rimangono verticali al variare degli appoggi. La prova completa in Play resta da fare.</p><p>Il campione deve ancora raggiungere la ricchezza dei riferimenti nei materiali, nelle persiane, nelle ringhiere e nei raccordi a terra. Le viste moderne non documentano il paese nel 1980. Gli altri lotti non sono stati ancora popolati.</p></section></main><script>document.querySelectorAll('section input').forEach(input=>input.addEventListener('input',()=>{const box=input.closest('section').querySelector('.compare');box.querySelector('.before').style.clipPath=`inset(0 ${100-input.value}% 0 0)`;box.querySelector('.line').style.left=input.value+'%'}));</script></html>'''
(root/'Confronto_dettagli.html').write_text(html,encoding='utf-8')
print(root/'Confronto_dettagli.html')
